parameters:
#    lapaillasse_user.example.class: Lapaillasse\UserBundle\Example

services:
#    lapaillasse_user.example:
#        class: %lapaillasse_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
