parameters:
#    lapaillasse_user.example.class: Lapaillasse\UserBundle\Example

services:
#    lapaillasse_user.example:
#        class: %lapaillasse_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lapaillasse_user.registration.form.type:
        class: Lapaillasse\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: lapaillasse_user_registration }