lapaillasse_campaign_homepage:
    pattern:  /
    defaults: { _controller: LapaillasseCampaignBundle:Default:index }

lapaillasse_campaign_mappage:
    pattern:  /map/
    defaults: { _controller: LapaillasseCampaignBundle:Default:map }